[client]
showErrorDetails = false

[theme]
base = "dark"
primaryColor = "#1D1D1B"
backgroundColor = "#E9E8E4"
secondaryBackgroundColor = "#ffffff"
textColor = "#B00005"

# Rouge : #B00005
# Rouge clair : #DF999B
# Noir : #1D1D1B
# Blanc : #ffffff
# Gris clair : #E9E8E4
