[client]
showErrorDetails = false

[theme]
base = "dark"
primaryColor = "#4B2E83"  # Violet ESCP
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Rouge : #B00005
# Rouge clair : #DF999B
# Noir : #1D1D1B
# Blanc : #ffffff
# Gris clair : #E9E8E4
