OPENAI_API_KEY = "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"

# Chemin vers le fichier JSON Firebase
FIREBASE_JSON_PATH = "auth_firebase/prompt-battle-9b72d-firebase-adminsdk-lhuc9-cc4c55a33e.json"
